-- ================================================================
-- PROCEDURE: sp_hello_world2
-- ================================================================
--
-- Description: No description available
--
-- Parameters:
--   (no parameters)
--

-- Created: 2025-09-12T23:18:33.000Z
-- Modified: 2025-09-12T23:18:33.000Z
-- Environment: dev
-- Database: public
--
-- Generated by: Enhanced DB Schema Analyzer
-- Generated at: 2025-09-12T23:52:10.983Z
-- ================================================================

DROP PROCEDURE IF EXISTS `sp_hello_world2`;

DELIMITER ;;

CREATE PROCEDURE `sp_hello_world2`()
BEGIN
    BEGIN
        SELECT 'Hello from Stored Procedure!' AS message;
    END
END

;;

DELIMITER ;
