-- ================================================================
-- PROCEDURE: sp_hello_world5
-- ================================================================
--
-- Description: No description available
--
-- Parameters:
--   (no parameters)
--

-- Created: 2025-09-13T15:30:36.000Z
-- Modified: 2025-09-13T15:30:36.000Z
-- Environment: dev
-- Database: public
--
-- Generated by: Enhanced DB Schema Analyzer
-- ================================================================

DROP PROCEDURE IF EXISTS `sp_hello_world5`;

DELIMITER ;;

CREATE PROCEDURE `sp_hello_world5`()
BEGIN
    BEGIN
        SELECT 'Hello from Stored Procedure!' AS message;
    END
END

;;

DELIMITER ;
