-- ================================================================
-- PROCEDURE: sp_hello_world3
-- ================================================================
--
-- Description: No description available
--
-- Parameters:
--   (no parameters)
--

-- Created: 2025-09-13T00:01:48.000Z
-- Modified: 2025-09-13T00:01:48.000Z
-- Environment: dev
-- Database: public
--
-- Generated by: Enhanced DB Schema Analyzer
-- Generated at: 2025-09-13T09:26:37.106Z
-- ================================================================

DROP PROCEDURE IF EXISTS `sp_hello_world3`;

DELIMITER ;;

CREATE PROCEDURE `sp_hello_world3`()
BEGIN
    BEGIN
        SELECT 'Hello from Stored Procedure!' AS message;
    END
END

;;

DELIMITER ;
