-- ================================================================
-- PROCEDURE: sp_hello_world1
-- ================================================================
--
-- Description: No description available
--
-- Parameters:
--   (no parameters)
--

-- Created: 2025-09-12T23:02:23.000Z
-- Modified: 2025-09-12T23:02:23.000Z
-- Environment: dev
-- Database: public
--
-- Generated by: Enhanced DB Schema Analyzer
-- ================================================================

DROP PROCEDURE IF EXISTS `sp_hello_world1`;

DELIMITER ;;

CREATE PROCEDURE `sp_hello_world1`()
BEGIN
    BEGIN
        SELECT 'Hello from Stored Procedure!' AS message;
    END
END

;;

DELIMITER ;
