-- ================================================================
-- FUNCTION: fn_hello_world3
-- ================================================================
--
-- Description: No description available
--
-- Parameters:
--   (no parameters)
--
-- Returns: varchar(100)
-- Created: 2025-09-13T00:01:48.000Z
-- Modified: 2025-09-13T00:01:48.000Z
-- Environment: dev
-- Database: public
--
-- Generated by: Enhanced DB Schema Analyzer
-- Generated at: 2025-09-13T09:26:37.107Z
-- ================================================================

DROP FUNCTION IF EXISTS `fn_hello_world3`;

DELIMITER ;;

CREATE FUNCTION `fn_hello_world3`()
RETURNS varchar(100)
READS SQL DATA
DETERMINISTIC
BEGIN
    BEGIN
        RETURN 'Hello from Function!';
    END
END

;;

DELIMITER ;
