-- ================================================================
-- FUNCTION: fn_hello_world5
-- ================================================================
--
-- Description: No description available
--
-- Parameters:
--   (no parameters)
--
-- Returns: varchar(100)
-- Created: 2025-09-13T15:30:37.000Z
-- Modified: 2025-09-13T15:30:37.000Z
-- Environment: dev
-- Database: public
--
-- Generated by: Enhanced DB Schema Analyzer
-- ================================================================

DROP FUNCTION IF EXISTS `fn_hello_world5`;

DELIMITER ;;

CREATE FUNCTION `fn_hello_world5`()
RETURNS varchar(100)
READS SQL DATA
DETERMINISTIC
BEGIN
    BEGIN
        RETURN 'Hello from Function!';
    END
END

;;

DELIMITER ;
