-- ================================================================
-- FUNCTION: fn_hello_world2
-- ================================================================
--
-- Description: No description available
--
-- Parameters:
--   (no parameters)
--
-- Returns: varchar(100)
-- Created: 2025-09-12T23:18:32.000Z
-- Modified: 2025-09-12T23:18:32.000Z
-- Environment: dev
-- Database: public
--
-- Generated by: Enhanced DB Schema Analyzer
-- Generated at: 2025-09-13T09:08:24.100Z
-- ================================================================

DROP FUNCTION IF EXISTS `fn_hello_world2`;

DELIMITER ;;

CREATE FUNCTION `fn_hello_world2`()
RETURNS varchar(100)
READS SQL DATA
DETERMINISTIC
BEGIN
    BEGIN
        RETURN 'Hello from Function!';
    END
END

;;

DELIMITER ;
